
name: german_ai_pro
description: Final German AI Pro App
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

flutter:
  uses-material-design: true
